[package]
name = "watershell"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
pnet = "0.30.0"
regex = "1.6.0"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
